<?php

//so_feedsagent_connector_pericles

/*
 * Implementation of hook_so_feedsagent_connectors()
 */
function so_feedsagent_connector_pericles_so_feedsagent_connectors() {
    return array(
        'pericles' => array(
            'label' => "Périclès",
            'module' => 'so_feedsagent_connector_pericles',
            'class' => 'SoFeedsAgentConnectorPericles',
        )
    );
}

function so_feedsagent_connector_pericles_get_types_offres($index = null) {
    $types = array(
        1 => "vente appart",
        2 => "vente maison",
        3 => "vente terrain",
        4 => "vente immeuble",
        5 => "vente local",
        6 => "vente fdc",
        7 => "vente parking",
        11 => "location appart",
        12 => "location mais",
        13 => "location local",
        14 => "location parking",
        21 => "programme",
    );

    return $index === null ? $types : $types[$index];
}

/**
 * Unzip function
 *
 * @param string $filename : without extension
 * @param string $upload_directory : with scheme
 * @param string $connector_id
 *
 * @return string : the absolute path to the files.
 */
function so_feedsagent_connector_pericles_inflate_archive($filename, $upload_directory, $connector_id) {

    $file_time = filemtime($upload_directory . '/' . $filename . '.zip');
    $file_date = DateTime::createFromFormat('U', $file_time)->setTimezone(new DateTimeZone('Europe/Paris'))->format('Ymd');
    $target_directory = $upload_directory . '/' . $file_date . '_' . $connector_id;

    if(!is_dir($target_directory)) {
        $archive = new ZipArchive();
        $archive->open($upload_directory .'/' . $filename . '.zip');
        $archive->extractTo($target_directory);
        $archive->close();
    }

    return $target_directory;
}

/*
 * Implementation of hook_sfa_generator_form_map()
 */
function so_feedsagent_connector_pericles_sfa_generator_form_map() {

    $form_map = array(
        'pericles_new' => array(
            'label' => t("Define and map a Périclès virtual type"),
            'steps' => array(
                1 => array(
                    'title' => t("Périclès connector"),
                    'help' => "",
                    'previous_button' => false,
                    'function' => 'so_feedsagent_generator_virtual_type_params_step',
                    'args' => array(
                        'needs' => array(
                            array(
                                'param' => 'connector',
                                'args' => array(
                                    'type' => 'pericles',
                                    'label' => t("Use"),
                                    'weight' => 1,
                                ),
                            ),
                        ),
                    ),
                ),
                2 => array(
                    'title' => t("Mapping parameters"),
                    'help' => "",
                    'previous_button' => false,
                    'method' => 'generatorMappingParamsStep',
                    'args' => array(
                        'needs' => array(
                            array(
                                'param' => 'primary_type',
                                'args' => array(
                                    'orphans' => true,
                                    'filter' => 'orphans_only',
                                    'label' => t("Map from orphan virtual type"),
                                    'null_label' => "- " . t("no") . " -",
                                    'weight' => 1,
                                ),
                            ),
                            array(
                                'param' => 'drupal_type',
                                'args' => array(
                                    'label' => t("Drupal type mapping target"),
                                    'null_label' => "- " . t("create a new one") . " -",
                                    'index' => 'type',
                                    'weight' => 2,
                                ),
                            ),
                        ),
                    ),
                ),
                3 => array(
                    'title' => t("Périclès data"),
                    'help' => "",
                    'previous_button' => false, // disabled - @see bug
                    'method' => 'generatorListingParamsStep',
                    'args' => array(),
                ),
                4 => array(
                    'title' => t("Fields to unionize"),
                    'help' => "",
                    'previous_button' => false, // disabled - @see bug
                    'function' => 'so_feedsagent_generator_feed_fields_step',
                    'args' => array(),
                ),
                5 => array(
                    'title' => t("Fields definitions and mappings"),
                    'help' => t("'Title' parameter : if one or more values have been set in feed/connector, they can be overridden partially or totally, with correct index assignement."),
                    'previous_button' => false, // disabled - @see bug
                    'function' => 'so_feedsagent_generator_fields_definition_step',
                    'args' => array(),
                ),
                6 => array(
                    'title' => t("Media params"),
                    'help' => "",
                    'previous_button' => false, // disabled - @see bug
                    'function' => 'so_feedsagent_generator_widgets_options_step',
                    'args' => array(),
                ),
                7 => array(
                    'title' => t("Drupal new node type params"),
                    'help' => "",
                    'previous_button' => false, // disabled - @see bug
                    'function' => 'so_feedsagent_generator_content_type_params_step',
                    'args' => array(),
                ),
                8 => array(
                    'title' => "Type registration",
                    'help' => "",
                    'previous_button' => false,
                    'function' => 'so_feedsagent_generator_type_registration_step',
                    'args' => array(),
                ),
            ),
        ),

        'pericles_edit' => array(
            'label' => t("Edit a Périclès virtual type"),
            'steps' => array(
                1 => array(
                    'title' => t("Périclès connector"),
                    'help' => "",
                    'previous_button' => false,
                    'function' => 'so_feedsagent_generator_virtual_type_params_step',
                    'args' => array(
                        'needs' => array(
                            array(
                                'param' => 'connector',
                                'args' => array(
                                    'type' => 'pericles',
                                    'label' => t("Edit virtual types which use"),
                                    'weight' => 1,
                                ),
                            ),
                        ),
                    ),
                ),
                2 => array(
                    'title' => t("Virtual type"),
                    'help' => "",
                    'previous_button' => false,
                    'method' => 'generatorEditVirtualParamsStep',
                    'args' => array(
                        'needs' => array(
                            array(
                                'param' => 'primary_type',
                                'args' => array(
                                    'orphans' => false,
                                    'label' => null,
                                    'null_option' => false,
                                ),
                            ),
                        ),
                    ),
                ),
                3 => array(
                    'title' => t("Mapping parameters"),
                    'help' => "",
                    'previous_button' => false, // disabled - @see bug
                    'method' => 'generatorMappingParamsStep',
                    'args' => array(
                        'needs' => array(
                            array(
                                'param' => 'drupal_type',
                                'args' => array(
                                    'label' => t("Drupal type mapping target"),
                                    'null_label' => "- " . t("create a new one") . " -",
                                    'index' => 'type',
                                    'weight' => 2,
                                ),
                            ),
                        ),
                    ),
                ),
                4 => array(
                    'title' => t("Périclès data"),
                    'help' => "",
                    'previous_button' => false, // disabled - @see bug
                    'method' => 'generatorListingParamsStep',
                    'args' => array(),
                ),
                5 => array(
                    'title' => t("Fields to unionize"),
                    'help' => "",
                    'previous_button' => false, // disabled - @see bug
                    'function' => 'so_feedsagent_generator_feed_fields_step',
                    'args' => array(),
                ),
                6 => array(
                    'title' => t("Fields definitions and mappings"),
                    'help' => t("'Title' parameter : if one or more values have been set in feed/connector, they can be overridden partially or totally, with correct index assignement."),
                    'previous_button' => false, // disabled - @see bug
                    'function' => 'so_feedsagent_generator_fields_definition_step',
                    'args' => array(),
                ),
                7 => array(
                    'title' => t("Media params"),
                    'help' => "",
                    'previous_button' => false, // disabled - @see bug
                    'function' => 'so_feedsagent_generator_widgets_options_step',
                    'args' => array(),
                ),
                8 => array(
                    'title' => t("Drupal new node type params"),
                    'help' => "",
                    'previous_button' => false, // disabled - @see bug
                    'function' => 'so_feedsagent_generator_content_type_params_step',
                    'args' => array(),
                ),
                9 => array(
                    'title' => "Type registration",
                    'help' => "",
                    'previous_button' => false,
                    'function' => 'so_feedsagent_generator_type_registration_step',
                    'args' => array(),
                ),
            ),
        ),
    );

    return $form_map;
}